language: python
cache:
  - pip
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - 3.5-dev
  - '3.6'
  - 3.6-dev
before_install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install -U wheel
  - pip install flake8
install:
  - pip install tox-travis .[test]
script:
  - flake8 niet
  - python setup.py install
  - niet tests/samples/sample.yaml project.meta.name
  - niet tests/samples/sample.yaml project.meta.tags

deploy:
  - provider: pypi
    user: 4383
    password:
      secure: nCzmcLl34+KqzguQSYO1cWt20RuJ47Xfr7Bawz8ZNzmLf/lC5w4nPhi58thNdu6uFoGgraHlnK49OviP1H5NnImlxWooVWwWyjvwyKI7zT9FpocTuUphCfrqsMF4q9AjmredaazlFR5zAxA73uHCTX9T0Ehu6qF4jG+o+qqqkiP2UiF0AAyP2xVa2m9J6AMpPGGgSvp0/xJYlVQ9o6uAEafk6xBNJxxDcKWGwwjU9VFfUSC5XUAWIeuWEMqO2AJgBEV8pUVMfLZvaVjx2caq2SBUdFrTPqVYRcXHBE/fS/sdczjRYo0SCG2D8sZdtWUqSozcZ1ct1c1LcQI3bMeoEc7WBh0vk5ej7wqnd6DFp/xqmfhgUQx+UwnT7anl1laDXkmPOQK1xRWJA2aghI57u2jahxUqnS7HlL0S6kS0/SjsV9ar5/l8OjHeTDJylwvLGcvCp839cUgnZ1Yx1+nblqDacAWpUw2P6fXvESpkh1pT7AIcEKsFBUpVEqFByh7CtTIZqp8QOyQJYBznoUPLLRcIORPwIQoEzO2VSRmcaR7Ev6LLDYNqnMb8boRDNlDmWE4JTcYBzByIcNi6LC7KSaSqGYfbugXHTHwXQQxDUBDEkAJVlM3RooRQjAE9HtXtSTAKZYFpu66HdxMIIX0wqiOAXar88cz9GrXqh/T0kBs=
    on:
      tags: true
    distributions: sdist bdist_wheel

    #- provider: pypi
    #- user: 4383
    #- password:
    #-   secure: "nR3B3hnD2idXB4bi4AphCbuEDtRfh0PeQtbKwM340FOqluIxMBp0tjlAAHKi1F7IaSIcZFM65tu5jbZiww6NuFPpG2JSRRMfDM0F9uvveay/ikr/5UQ74a9gK94nXoKaQLdB9fy6KvogL2ZkDIfhfwWxCHnyAeftstPGJH44Y3LXWKDyQNq/vXVPxqooMo4XIOMZmMvldjt7P9AE3DKadQnXzrH049XT00kruH0UIvKHej4IiPDOPhDpd9TZPti7yxWE795ZRuzUKw3PWsKvl0+cpZwFsrzOy5TLULQU2VY8SfPjmO29FAY4jL9qcmO/gQRd+E4RtIGMiB0cWQBYshx9sGKwTcFcm48YLHTJAPZZdj5HE21Wa4Womx3ZKJNjTaa7ymkf+511n8eHG9w4oEePgyzurqhIDUoeBYzkqfbsUbM+Q22+Rm0pwaGaUtWOBM6VxGl4F/3ci886uSggBDMoLas+KzV1sbU8RK+1Hn3M/bcINuFFAgxt48xKpG2dTOC8dfaW7ffaFyxM5y3/GGJ/WmsbGktB7Gzjl1d5Y8INt6dPAWYoWoSfdmqk8q9vsgnRnL/poaewDGAoDVvlxsfaz17apRzzWL4y9lr5VOcGSEsKbFEKJw05nq5zGSPuixJkoPw1KRAnCOm5UhBBB+rd1pmrnZncYAdl+59jFGc="
    #- on:
    #-   branch: devel
    #- server: https://test.pypi.org/legacy/
    #- distributions: sdist bdist_wheel
